### ISSUE TITLE
Reduce credential cache TTL

### ISSUE THREAD

**Issue by jradtilbrook** [HealthEngineAU/laravel-easy-aws#2]
In laravel versions prior to 5.8 (and possible even 5.8+) the cache TTL is passed in as seconds to the cache provider but divided by 60 and rounded up to pass to the older laravel cache version that works with minutes.

I have seen instances where this cache TTL is too long and still provides credentials from the cache that are actually expired.

I propose that this cache adapter package trim a few seconds of the TTL that is passed in to guarantee that the credentials will still be valid once they are retrieved, rather than serving credentials that are expired. It means that they will be refreshed more often than required but should provide a much more robust caching experience that never gives back expired credentials.

Note: converting the `ceil` to `floor` could be enough, but I don't think it would hurt to just remove 30 seconds from the provided TTL, given that the AWS package passes the expiry of the credentials to this package.

**Comment by nathanblogs** [comment]
I thought about reducing the expiry, however there might be an upstream services that is already caching tokens, therefore fetching a new token could only have a 30 seconds expiry and I don't like the idea of adding additional logic to handle that.
